#!/usr/bin/env python3

import argparse
import os
import subprocess
import sys

parser = argparse.ArgumentParser()
parser.add_argument("--gpu",
    action="store_true", help="Enable virtio-gpu/virgl passthrough")
args = parser.parse_args()

os.chdir(os.path.dirname(os.path.realpath(__file__)))

if not os.path.exists("id_ed25519"):
    subprocess.check_call([
        "ssh-keygen", "-t", "ed25519", "-f", "id_ed25519",
        "-N", "", "-C", "pywl-vm",
    ])

env = {**os.environ, "ARG_GPU": "1" if args.gpu else "0"}

sys.exit(subprocess.call([
    "nix-build", "<nixpkgs/nixos>", "-A", "vm",
    "-I", "nixos-config=./config.nix",
], env=env))
